<?php
	require_once 'connect.php';
$sql = "SELECT * FROM `connect.php`;";
echo '<!DOCTYPE html>'
echo '<html class="no-js" lang="en">'
echo ''
echo '<head>'
echo '<meta charset="utf-8" />'
echo '<title>Nest - Multipurpose eCommerce HTML Template</title>'
echo '<meta http-equiv="x-ua-compatible" content="ie=edge" />'
echo '<meta name="description" content="" />'
echo '<meta name="viewport" content="width=device-width, initial-scale=1" />'
echo '<meta property="og:title" content="" />'
echo '<meta property="og:type" content="" />'
echo '<meta property="og:url" content="" />'
echo '<meta property="og:image" content="" />'
echo '<!-- Favicon -->'
echo '<link rel="shortcut icon" type="image/x-icon" href="assets/imgs/theme/favicon.svg" />'
echo '<!-- Template CSS -->'
echo '<link rel="stylesheet" href="assets/css/main.css?v=5.6" />'
echo '</head>'
echo ''
echo '<body>'
echo '<!-- Quick view -->'
echo '<div class="modal fade custom-modal" id="quickViewModal" tabindex="-1" aria-labelledby="quickViewModalLabel" aria-hidden="true">'
echo '<div class="modal-dialog">'
echo '<div class="modal-content">'
echo '<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>'
echo '<div class="modal-body">'
echo '<div class="row">'
echo '<div class="col-md-6 col-sm-12 col-xs-12 mb-md-0 mb-sm-5">'
echo '<div class="detail-gallery">'
echo '<span class="zoom-icon"><i class="fi-rs-search"></i></span>'
echo '<!-- MAIN SLIDES -->'
echo '<div class="product-image-slider">'
echo '<figure class="border-radius-10">'
echo '<img src="assets/imgs/shop/product-16-2.webp" alt="Корзина WEBP" />'
echo '</figure>'
echo '<figure class="border-radius-10">'
echo '<img src="assets/imgs/shop/product-16-1.jpg" alt="product ГЕРБ" />'
echo '</figure>'
echo '<figure class="border-radius-10">'
echo '<img src="assets/imgs/shop/product-16-3.jpg" alt="product image" />'
echo '</figure>'
echo '<figure class="border-radius-10">'
echo '<img src="assets/imgs/shop/product-16-4.jpg" alt="product image" />'
echo '</figure>'
echo '<figure class="border-radius-10">'
echo '<img src="assets/imgs/shop/product-16-5.jpg" alt="product image" />'
echo '</figure>'
echo '<figure class="border-radius-10">'
echo '<img src="assets/imgs/shop/product-16-6.jpg" alt="product image" />'
echo '</figure>'
echo '<figure class="border-radius-10">'
echo '<img src="assets/imgs/shop/product-16-7.jpg" alt="product image" />'
echo '</figure>'
echo '</div>'
echo '<!-- THUMBNAILS -->'
echo '<div class="slider-nav-thumbnails">'
echo '<div><img src="assets/imgs/shop/thumbnail-3.WEBP" alt="product WEBP" /></div>'
echo '<div><img src="assets/imgs/shop/thumbnail-4.jpg" alt="product image" /></div>'
echo '<div><img src="assets/imgs/shop/thumbnail-5.jpg" alt="product image" /></div>'
echo '<div><img src="assets/imgs/shop/thumbnail-6.jpg" alt="product image" /></div>'
echo '<div><img src="assets/imgs/shop/thumbnail-7.jpg" alt="product image" /></div>'
echo '<div><img src="assets/imgs/shop/thumbnail-8.jpg" alt="product image" /></div>'
echo '<div><img src="assets/imgs/shop/thumbnail-9.jpg" alt="product image" /></div>'
echo '</div>'
echo '</div>'
echo '<!-- End Gallery -->'
echo '</div>'
echo '<div class="col-md-6 col-sm-12 col-xs-12">'
echo '<div class="detail-info pr-30 pl-30">'
echo '<span class="stock-status out-stock"> Распродажа снята </span>'
echo '<h3 class="title-detail"><a href="shop-product-right.html" class="text-heading">Букет кустовой розы</a></h3>'
echo '<div class="product-detail-rating">'
echo '<div class="product-rate-cover text-end">'
echo '<div class="product-rate d-inline-block">'
echo '<div class="product-rating" style="width: 90%"></div>'
echo '</div>'
echo '<span class="font-small ml-5 text-muted"> (101 Отзыва)</span>'
echo '</div>'
echo '</div>'
echo '<div class="clearfix product-price-cover">'
echo '<div class="product-price primary-color float-left">'
echo '<span class="current-price text-brand">1000р.</span>'
echo '<span>'
echo '<span class="save-price font-md color3 ml-15">20%</span>'
echo '<span class="old-price font-md ml-15">1200р.</span>'
echo '</span>'
echo '</div>'
echo '</div>'
echo '<div class="detail-extralink mb-30">'
echo '<div class="detail-qty border radius">'
echo '<a href="#" class="qty-down"><i class="fi-rs-angle-small-down"></i></a>'
echo '<span class="qty-val">1</span>'
echo '<a href="#" class="qty-up"><i class="fi-rs-angle-small-up"></i></a>'
echo '</div>'
echo '<div class="product-extra-link2">'
echo '<button type="submit" class="button button-add-to-cart"><i class="fi-rs-shopping-cart"></i>Add to cart</button>'
echo '</div>'
echo '</div>'
echo '<div class="font-xs">'
echo '<ul>'
echo '<li class="mb-5">Vendor: <span class="text-brand">Nest</span></li>'
echo '<li class="mb-5">MFG:<span class="text-brand"> Jun 4.2022</span></li>'
echo '</ul>'
echo '</div>'
echo '</div>'
echo '<!-- Detail Info -->'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<header class="header-area header-style-1 header-height-2">'
echo '<div class="mobile-promotion">'
echo '<span><strong>PRINCE FLOWERS USHAKOV</strong><br>"Верность и постоянство"</span>'
echo '</div>'
echo '<div class="header-top header-top-ptb-1 d-none d-lg-block">'
echo '<div class="container">'
echo '<div class="row align-items-center">'
echo '<div class="col-xl-3 col-lg-4">'
echo '<div class="header-info">'
echo '<ul>'
echo '<li><a href="page-about.htlm">О нас</a></li>'
echo '<li><a href="page-account.html">Мой аккаунт</a></li>'
echo '<li><a href="shop-wishlist.html">Список желаний</a></li>'
echo '<li><a href="shop-order.html">Отслеживание заказов</a></li>'
echo '</ul>'
echo '</div>'
echo '</div>'
echo '<div class="col-xl-6 col-lg-4">'
echo '<div class="text-center">'
echo '<div id="news-flash" class="d-inline-block">'
echo '<ul>'
echo '<li>Самые свежие цветы</li>'
echo '<li>Фото букета перед отравкой</li>'
echo '<li>Открытка в подарок</li>'
echo '<li>Доставка в пределах МКАД бесплатно</li>'
echo '</ul>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="col-xl-3 col-lg-4">'
echo '<div class="header-info header-info-right">'
echo '<ul>'
echo '<li>Нужна помощь? Позвоните нам: <strong class="text-brand"><a href="tel:+79162858833">+7 916 285 88 33</a></strong></li>'
echo ''
echo '</ul>'
echo '</li>'
echo '</ul>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo ''
echo '<div class="header-middle header-middle-ptb-1 d-none d-lg-block">'
echo '<div class="container">'
echo '<div class="header-wrap">'
echo '<div class="logo logo-width-1">'
echo '<a href="index.html"><img src="assets/imgs/theme/логом.png" width="150" height="100" alt="logo" /></a>'
echo ''
echo '</div>'
echo ''
echo '<span><strong>PRINCE FLOWERS USHAKOV<br>"Верность и постоянство"</strong></span>'
echo '<div class="header-right">'
echo '<div class="search-style-2">'
echo '<form action="#">'
echo '<select class="select-active">'
echo '<option>Все категории</option>'
echo '<option>Milks and Dairies</option>'
echo '<option>Wines & Alcohol</option>'
echo '<option>Clothing & Beauty</option>'
echo '<option>Pet Foods & Toy</option>'
echo '<option>Fast food</option>'
echo '<option>Baking material</option>'
echo '<option>Vegetables</option>'
echo '<option>Fresh Seafood</option>'
echo '<option>Noodles & Rice</option>'
echo '<option>Ice cream</option>'
echo '</select>'
echo '<input type="text" placeholder="Поиск товара..." />'
echo '</form>'
echo '</div>'
echo ''
echo '<div class="header-action-right">'
echo '<div class="header-action-2">'
echo '<div class="search-location">'
echo '<form action="#">'
echo '<select class="select-active">'
echo '<option>Yo</option>'
echo '<option>Alabama</option>'
echo '<option>Alaska</option>'
echo '<option>Arizona</option>'
echo '<option>Delaware</option>'
echo '<option>Florida</option>'
echo '<option>Georgia</option>'
echo '<option>Hawaii</option>'
echo '<option>Indiana</option>'
echo '<option>Maryland</option>'
echo '<option>Nevada</option>'
echo '<option>New Jersey</option>'
echo '<option>New Mexico</option>'
echo '<option>New York</option>'
echo '</select>'
echo '</form>'
echo '</div>'
echo '<div class="header-action-icon-2">'
echo '<a href="shop-compare.html">'
echo '<img class="svgInject" alt="Nest" src="assets/imgs/theme/icons/icon-compare.svg" />'
echo '<span class="pro-count blue">3</span>'
echo '</a>'
echo '<a href="shop-compare.html"><span class="lable ml-0">Сравнить</span></a>'
echo '</div>'
echo '<div class="header-action-icon-2">'
echo '<a href="shop-wishlist.html">'
echo '<img class="svgInject" alt="Nest" src="assets/imgs/theme/icons/icon-heart.svg" />'
echo '<span class="pro-count blue">6</span>'
echo '</a>'
echo '<a href="shop-wishlist.html"><span class="lable">Список желаний</span></a>'
echo '</div>'
echo '<div class="header-action-icon-2">'
echo '<a class="mini-cart-icon" href="shop-cart.html">'
echo '<img alt="Nest" src="assets/imgs/theme/icons/icon-cart.svg" />'
echo '<span class="pro-count blue">2</span>'
echo '</a>'
echo '<a href="shop-cart.html"><span class="lable">Корзина</span></a>'
echo '<div class="cart-dropdown-wrap cart-dropdown-hm2">'
echo '<ul>'
echo '<li>'
echo '<div class="shopping-cart-img">'
echo '<a href="shop-product-right.html"><img alt="Nest" src="assets/imgs/shop/thumbnail-3.jpg" /></a>'
echo '</div>'
echo '<div class="shopping-cart-title">'
echo '<h4><a href="shop-product-right.html">Daisy Casual Bag</a></h4>'
echo '<h4><span>1 × </span>$800.00</h4>'
echo '</div>'
echo '<div class="shopping-cart-delete">'
echo '<a href="#"><i class="fi-rs-cross-small"></i></a>'
echo '</div>'
echo '</li>'
echo '<li>'
echo '<div class="shopping-cart-img">'
echo '<a href="shop-product-right.html"><img alt="Nest" src="assets/imgs/shop/thumbnail-2.jpg" /></a>'
echo '</div>'
echo '<div class="shopping-cart-title">'
echo '<h4><a href="shop-product-right.html">Corduroy Shirts</a></h4>'
echo '<h4><span>1 × </span>$3200.00</h4>'
echo '</div>'
echo '<div class="shopping-cart-delete">'
echo '<a href="#"><i class="fi-rs-cross-small"></i></a>'
echo '</div>'
echo '</li>'
echo '</ul>'
echo '<div class="shopping-cart-footer">'
echo '<div class="shopping-cart-total">'
echo '<h4>Total <span>$4000.00</span></h4>'
echo '</div>'
echo '<div class="shopping-cart-button">'
echo '<a href="shop-cart.html" class="outline">View cart</a>'
echo '<a href="shop-checkout.html">Checkout</a>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="header-action-icon-2">'
echo '<a href="page-account.html">'
echo '<img class="svgInject" alt="Nest" src="assets/imgs/theme/icons/icon-user.svg" />'
echo '</a>'
echo '<a href="page-account.html"><span class="lable ml-0">Учетная запись</span></a>'
echo '<div class="cart-dropdown-wrap cart-dropdown-hm2 account-dropdown">'
echo '<ul>'
echo '<li><a href="page-account.html"><i class="fi fi-rs-user mr-10"></i>Мой Аккаунт</a></li>'
echo '<li><a href="page-account.html"><i class="fi fi-rs-location-alt mr-10"></i>Отслеживание заказов</a></li>'
echo '<li><a href="page-account.html"><i class="fi fi-rs-label mr-10"></i>Мой Ваучер</a></li>'
echo '<li><a href="shop-wishlist.html"><i class="fi fi-rs-heart mr-10"></i>Мои желания</a></li>'
echo '<li><a href="page-account.html"><i class="fi fi-rs-settings-sliders mr-10"></i>Настройка</a></li>'
echo '<li><a href="page-login.html"><i class="fi fi-rs-sign-out mr-10"></i>Выход</a></li>'
echo '</ul>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo ''
echo ''
echo '<!---------------------------------------------ШАПКА МОБИЛА главная сайта------------------------------------------------------------->'
echo '<div class="header-bottom header-bottom-bg-color sticky-bar">'
echo '<div class="container">'
echo '<div class="single-mobile-header-info">'
echo ''
echo '</div>'
echo ''
echo ''
echo '<div class="header-wrap header-space-between position-relative">'
echo '<div class="logo logo-width-1 d-block d-lg-none">'
echo '<a href="index.html"><img src="assets/imgs/theme/логом.png" width="80" height="70" alt="logo" /></a>'
echo ''
echo '</div>'
echo ''
echo ''
echo '<div class="header-nav d-none d-lg-flex">'
echo '<div class="main-categori-wrap d-none d-lg-block">'
echo '<a class="categories-button-active" href="#">'
echo '<span class="fi-rs-apps"></span> <span class="et">Выбор</span> Категории'
echo '<i class="fi-rs-angle-down"></i>'
echo '</a>'
echo '<div class="categories-dropdown-wrap categories-dropdown-active-large font-heading">'
echo '<div class="d-flex categori-dropdown-inner">'
echo '<ul>'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/category-1.svg" alt="" />Milks and Dairies</a>'
echo '</li>'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/category-2.svg" alt="" />Clothing & beauty</a>'
echo '</li>'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/category-3.svg" alt="" />Pet Foods & Toy</a>'
echo '</li>'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/category-4.svg" alt="" />Baking material</a>'
echo '</li>'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/category-5.svg" alt="" />Fresh Fruit</a>'
echo '</li>'
echo '</ul>'
echo '<ul class="end">'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/category-6.svg" alt="" />Wines & Drinks</a>'
echo '</li>'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/category-7.svg" alt="" />Fresh Seafood</a>'
echo '</li>'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/category-8.svg" alt="" />Fast food</a>'
echo '</li>'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/category-9.svg" alt="" />Vegetables</a>'
echo '</li>'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/category-10.svg" alt="" />Bread and Juice</a>'
echo '</li>'
echo '</ul>'
echo '</div>'
echo '<div class="more_slide_open" style="display: none">'
echo '<div class="d-flex categori-dropdown-inner">'
echo '<ul>'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/icon-1.svg" alt="" />Milks and Dairies</a>'
echo '</li>'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/icon-2.svg" alt="" />Clothing & beauty</a>'
echo '</li>'
echo '</ul>'
echo '<ul class="end">'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/icon-3.svg" alt="" />Wines & Drinks</a>'
echo '</li>'
echo '<li>'
echo '<a href="shop-grid-right.html"> <img src="assets/imgs/theme/icons/icon-4.svg" alt="" />Fresh Seafood</a>'
echo '</li>'
echo '</ul>'
echo '</div>'
echo '</div>'
echo '<div class="more_categories"><span class="icon"></span> <span class="heading-sm-1">Поиск товара...</span></div>'
echo '</div>'
echo '</div>'
echo '<div class="main-menu main-menu-padding-1 main-menu-lh-2 d-none d-lg-block font-heading">'
echo '<nav>'
echo '<ul>'
echo '<li class="hot-deals"><img src="assets/imgs/theme/icons/icon-hot.svg" width="25" height="35"  alt="hot deals" /><a href="shop-grid-right.html">Акции</a></li>'
echo '<li>'
echo '<a class="active" href="index.html">Главная <i class="fi-rs-angle-down"></i></a>'
echo '<ul class="sub-menu">'
echo '<li><a href="index.html">Home 1</a></li>'
echo '<li><a href="index-2.html">Home 2</a></li>'
echo '<li><a href="index-3.html">Home 3</a></li>'
echo '<li><a href="index-4.html">Home 4</a></li>'
echo '<li><a href="index-5.html">Home 5</a></li>'
echo '<li><a href="index-6.html">Home 6</a></li>'
echo '</ul>'
echo '</li>'
echo '<li>'
echo '<a href="page-about.html">О нас</a>'
echo '</li>'
echo '<li>'
echo '<a href="shop-grid-right.html">Магазин <i class="fi-rs-angle-down"></i></a>'
echo '<ul class="sub-menu">'
echo '<li><a href="shop-grid-right.html">Shop Grid – Right Sidebar</a></li>'
echo '<li><a href="shop-grid-left.html">Shop Grid – Left Sidebar</a></li>'
echo '<li><a href="shop-list-right.html">Shop List – Right Sidebar</a></li>'
echo '<li><a href="shop-list-left.html">Shop List – Left Sidebar</a></li>'
echo '<li><a href="shop-fullwidth.html">Shop - Wide</a></li>'
echo '<li>'
echo '<a href="#">Single Product <i class="fi-rs-angle-right"></i></a>'
echo '<ul class="level-menu">'
echo '<li><a href="shop-product-right.html">Product – Right Sidebar</a></li>'
echo '<li><a href="shop-product-left.html">Product – Left Sidebar</a></li>'
echo '<li><a href="shop-product-full.html">Product – No sidebar</a></li>'
echo '<li><a href="shop-product-vendor.html">Product – Vendor Infor</a></li>'
echo '</ul>'
echo '</li>'
echo '<li><a href="shop-filter.html">Shop – Filter</a></li>'
echo '<li><a href="shop-wishlist.html">Shop – Wishlist</a></li>'
echo '<li><a href="shop-cart.html">Shop – Cart</a></li>'
echo '<li><a href="shop-checkout.html">Shop – Checkout</a></li>'
echo '<li><a href="shop-compare.html">Shop – Compare</a></li>'
echo '<li>'
echo '<a href="#">Shop Invoice<i class="fi-rs-angle-right"></i></a>'
echo '<ul class="level-menu">'
echo '<li><a href="shop-invoice-1.html">Shop Invoice 1</a></li>'
echo '<li><a href="shop-invoice-2.html">Shop Invoice 2</a></li>'
echo '<li><a href="shop-invoice-3.html">Shop Invoice 3</a></li>'
echo '<li><a href="shop-invoice-4.html">Shop Invoice 4</a></li>'
echo '<li><a href="shop-invoice-5.html">Shop Invoice 5</a></li>'
echo '<li><a href="shop-invoice-6.html">Shop Invoice 6</a></li>'
echo '</ul>'
echo '</li>'
echo '</ul>'
echo '</li>'
echo ''
echo ''
echo '<li>'
echo '<a href="blog-category-grid.html">Блог <i class="fi-rs-angle-down"></i></a>'
echo '<ul class="sub-menu">'
echo '<li><a href="blog-category-grid.html">Blog Category Grid</a></li>'
echo '<li><a href="blog-category-list.html">Blog Category List</a></li>'
echo '<li><a href="blog-category-big.html">Blog Category Big</a></li>'
echo '<li><a href="blog-category-fullwidth.html">Blog Category Wide</a></li>'
echo '<li>'
echo '<a href="#">Single Post <i class="fi-rs-angle-right"></i></a>'
echo '<ul class="level-menu level-menu-modify">'
echo '<li><a href="blog-post-left.html">Left Sidebar</a></li>'
echo '<li><a href="blog-post-right.html">Right Sidebar</a></li>'
echo '<li><a href="blog-post-fullwidth.html">No Sidebar</a></li>'
echo '</ul>'
echo '</li>'
echo '</ul>'
echo '</li>'
echo '<li>'
echo '<a href="#">Страницы <i class="fi-rs-angle-down"></i></a>'
echo '<ul class="sub-menu">'
echo '<li><a href="page-about.html">О нас</a></li>'
echo '<li><a href="page-contact.html">Контакты</a></li>'
echo '<li><a href="page-account.html">Мой аккаунт</a></li>'
echo '<li><a href="page-login.html">Вход</a></li>'
echo '<li><a href="page-register.html">Регистрация</a></li>'
echo '<li><a href="page-forgot-password.html">Забыли пароль</a></li>'
echo '<li><a href="page-reset-password.html">Сбросить пароль</a></li>'
echo '<li><a href="page-purchase-guide.html">Руководство по покупке</a></li>'
echo '<li><a href="page-privacy-policy.html">Политика конфиденциальности</a></li>'
echo '<li><a href="page-terms.html">Условия обслуживания</a></li>'
echo '<li><a href="page-404.html">404 страница</a></li>'
echo '</ul>'
echo '</li>'
echo '<li>'
echo '<a href="page-contact.html">Контакты</a>'
echo '</li>'
echo '</ul>'
echo '</nav>'
echo '</div>'
echo '</div>'
echo '<div class="hotline d-none d-lg-flex">'
echo '<img src="assets/imgs/theme/трубка.svg" alt="Позвонить" width="40" height="40"/>'
echo ''
echo '<a title="Whatsapp" href="whatsapp://send?phone=79162858833"><img src="assets/imgs/theme/whatsapp.webp" alt="Написать в Whatsapp" width="40" height="40"/></a>'
echo ''
echo '<a href="https://telegram.im/@PRINCEFLOWERSUSHAKOV" target="_blank">'
echo '<img src="assets/imgs/theme/telegram.webp" alt="Написать в Telegram" width="40" height="40"/></a>'
echo ''
echo '</div>'
echo '<div class="header-action-icon-2 d-block d-lg-none">'
echo '<div class="burger-icon burger-icon-white">'
echo '<span class="burger-icon-top"></span>'
echo '<span class="burger-icon-mid"></span>'
echo '<span class="burger-icon-bottom"></span>'
echo '</div>'
echo '</div>'
echo '<div class="header-action-right d-block d-lg-none">'
echo '<div class="header-action-2">'
echo '<div class="header-action-icon-2">'
echo '<a href="shop-wishlist.html">'
echo '<img alt="Nest" src="assets/imgs/theme/icons/icon-heart.svg" />'
echo '<span class="pro-count white">4</span>'
echo '</a>'
echo '</div>'
echo '<div class="header-action-icon-2">'
echo '<a class="mini-cart-icon" href="shop-cart.html">'
echo '<img alt="Nest" src="assets/imgs/theme/icons/icon-cart.svg" />'
echo '<span class="pro-count white">2</span>'
echo '</a>'
echo '<div class="cart-dropdown-wrap cart-dropdown-hm2">'
echo '<ul>'
echo '<li>'
echo '<div class="shopping-cart-img">'
echo '<a href="shop-product-right.html"><img alt="Nest" src="assets/imgs/shop/thumbnail-3.WEBP" /></a>'
echo '</div>'
echo '<div class="shopping-cart-title">'
echo '<h4><a href="shop-product-right.html">Plain Striola Shirts</a></h4>'
echo '<h3><span>1 × </span>$800.00</h3>'
echo '</div>'
echo '<div class="shopping-cart-delete">'
echo '<a href="#"><i class="fi-rs-cross-small"></i></a>'
echo '</div>'
echo '</li>'
echo '<li>'
echo '<div class="shopping-cart-img">'
echo '<a href="shop-product-right.html"><img alt="Nest" src="assets/imgs/shop/thumbnail-4.jpg" /></a>'
echo '</div>'
echo '<div class="shopping-cart-title">'
echo '<h4><a href="shop-product-right.html">Macbook Pro 2022</a></h4>'
echo '<h3><span>1 × </span>$3500.00</h3>'
echo '</div>'
echo '<div class="shopping-cart-delete">'
echo '<a href="#"><i class="fi-rs-cross-small"></i></a>'
echo '</div>'
echo '</li>'
echo '</ul>'
echo '<div class="shopping-cart-footer">'
echo '<div class="shopping-cart-total">'
echo '<h4>Total <span>$383.00</span></h4>'
echo '</div>'
echo '<div class="shopping-cart-button">'
echo '<a href="shop-cart.html">View cart</a>'
echo '<a href="shop-checkout.html">Checkout</a>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</header>'
echo ''
echo '<!-------------------------------------------------------- mobile menu боковое -------------------------------------------------------------->'
echo ''
echo '<div class="mobile-header-active mobile-header-wrapper-style">'
echo '<div class="mobile-header-wrapper-inner">'
echo '<div class="mobile-header-top">'
echo '<div class="mobile-header-logo">'
echo '<a href="index.html"><img src="assets/imgs/theme/логом.png" width="80" height="60" alt="Логотип" /></a>'
echo ''
echo '</div>'
echo '<img src="assets/imgs/theme/трубка.svg" alt="Позвонить" width="40" height="40"/>'
echo ''
echo '<a title="Whatsapp" href="whatsapp://send?phone=79162858833"><img src="assets/imgs/theme/whatsapp.webp" alt="Написать в Whatsapp" width="40" height="40"/></a>'
echo ''
echo '<a href="https://telegram.im/@PRINCEFLOWERSUSHAKOV" target="_blank">'
echo '<img src="assets/imgs/theme/telegram.webp" alt="Написать в Telegram" width="40" height="40"/></a>'
echo ''
echo ''
echo ''
echo ''
echo ''
echo ''
echo '<div class="mobile-menu-close close-style-wrap close-style-position-inherit">'
echo '<button class="close-style search-close">'
echo '<i class="icon-top"></i>'
echo '<i class="icon-bottom"></i>'
echo '</button>'
echo '</div>'
echo '</div>'
echo '<div class="mobile-header-content-area">'
echo '<div class="mobile-search search-style-3 mobile-header-border">'
echo '<form action="#">'
echo '<input type="text" placeholder="Search for items…" />'
echo '<button type="submit"><i class="fi-rs-search"></i></button>'
echo '</form>'
echo '</div>'
echo '<div class="mobile-menu-wrap mobile-header-border">'
echo '<!-- mobile menu start -->'
echo '<nav>'
echo '<ul class="mobile-menu font-heading">'
echo '<li class="menu-item-has-children">'
echo '<a href="index.html">Home</a>'
echo '<ul class="dropdown">'
echo '<li><a href="index.html">Home 1</a></li>'
echo '<li><a href="index-2.html">Home 2</a></li>'
echo '<li><a href="index-3.html">Home 3</a></li>'
echo '<li><a href="index-4.html">Home 4</a></li>'
echo '<li><a href="index-5.html">Home 5</a></li>'
echo '<li><a href="index-6.html">Home 6</a></li>'
echo '</ul>'
echo '</li>'
echo '<li class="menu-item-has-children">'
echo '<a href="shop-grid-right.html">shop</a>'
echo '<ul class="dropdown">'
echo '<li><a href="shop-grid-right.html">Shop Grid – Right Sidebar</a></li>'
echo '<li><a href="shop-grid-left.html">Shop Grid – Left Sidebar</a></li>'
echo '<li><a href="shop-list-right.html">Shop List – Right Sidebar</a></li>'
echo '<li><a href="shop-list-left.html">Shop List – Left Sidebar</a></li>'
echo '<li><a href="shop-fullwidth.html">Shop - Wide</a></li>'
echo '<li class="menu-item-has-children">'
echo '<a href="#">Single Product</a>'
echo '<ul class="dropdown">'
echo '<li><a href="shop-product-right.html">Product – Right Sidebar</a></li>'
echo '<li><a href="shop-product-left.html">Product – Left Sidebar</a></li>'
echo '<li><a href="shop-product-full.html">Product – No sidebar</a></li>'
echo '<li><a href="shop-product-vendor.html">Product – Vendor Infor</a></li>'
echo '</ul>'
echo '</li>'
echo '<li><a href="shop-filter.html">Shop – Filter</a></li>'
echo '<li><a href="shop-wishlist.html">Shop – Wishlist</a></li>'
echo '<li><a href="shop-cart.html">Shop – Cart</a></li>'
echo '<li><a href="shop-checkout.html">Shop – Checkout</a></li>'
echo '<li><a href="shop-compare.html">Shop – Compare</a></li>'
echo '<li class="menu-item-has-children">'
echo '<a href="#">Shop Invoice</a>'
echo '<ul class="dropdown">'
echo '<li><a href="shop-invoice-1.html">Shop Invoice 1</a></li>'
echo '<li><a href="shop-invoice-2.html">Shop Invoice 2</a></li>'
echo '<li><a href="shop-invoice-3.html">Shop Invoice 3</a></li>'
echo '<li><a href="shop-invoice-4.html">Shop Invoice 4</a></li>'
echo '<li><a href="shop-invoice-5.html">Shop Invoice 5</a></li>'
echo '<li><a href="shop-invoice-6.html">Shop Invoice 6</a></li>'
echo '</ul>'
echo '</li>'
echo '</ul>'
echo '</li>'
echo '<li class="menu-item-has-children">'
echo '<a href="#">Vendors</a>'
echo '<ul class="dropdown">'
echo '<li><a href="vendors-grid.html">Vendors Grid</a></li>'
echo '<li><a href="vendors-list.html">Vendors List</a></li>'
echo '<li><a href="vendor-details-1.html">Vendor Details 01</a></li>'
echo '<li><a href="vendor-details-2.html">Vendor Details 02</a></li>'
echo '<li><a href="vendor-dashboard.html">Vendor Dashboard</a></li>'
echo '<li><a href="vendor-guide.html">Vendor Guide</a></li>'
echo '</ul>'
echo '</li>'
echo '<li class="menu-item-has-children">'
echo '<a href="#">Mega menu</a>'
echo '<ul class="dropdown">'
echo '<li class="menu-item-has-children">'
echo '<a href="#">Women's Fashion</a>'
echo '<ul class="dropdown">'
echo '<li><a href="shop-product-right.html">Dresses</a></li>'
echo '<li><a href="shop-product-right.html">Blouses & Shirts</a></li>'
echo '<li><a href="shop-product-right.html">Hoodies & Sweatshirts</a></li>'
echo '<li><a href="shop-product-right.html">Women's Sets</a></li>'
echo '</ul>'
echo '</li>'
echo '<li class="menu-item-has-children">'
echo '<a href="#">Men's Fashion</a>'
echo '<ul class="dropdown">'
echo '<li><a href="shop-product-right.html">Jackets</a></li>'
echo '<li><a href="shop-product-right.html">Casual Faux Leather</a></li>'
echo '<li><a href="shop-product-right.html">Genuine Leather</a></li>'
echo '</ul>'
echo '</li>'
echo '<li class="menu-item-has-children">'
echo '<a href="#">Technology</a>'
echo '<ul class="dropdown">'
echo '<li><a href="shop-product-right.html">Gaming Laptops</a></li>'
echo '<li><a href="shop-product-right.html">Ultraslim Laptops</a></li>'
echo '<li><a href="shop-product-right.html">Tablets</a></li>'
echo '<li><a href="shop-product-right.html">Laptop Accessories</a></li>'
echo '<li><a href="shop-product-right.html">Tablet Accessories</a></li>'
echo '</ul>'
echo '</li>'
echo '</ul>'
echo '</li>'
echo '<li class="menu-item-has-children">'
echo '<a href="blog-category-fullwidth.html">Blog</a>'
echo '<ul class="dropdown">'
echo '<li><a href="blog-category-grid.html">Blog Category Grid</a></li>'
echo '<li><a href="blog-category-list.html">Blog Category List</a></li>'
echo '<li><a href="blog-category-big.html">Blog Category Big</a></li>'
echo '<li><a href="blog-category-fullwidth.html">Blog Category Wide</a></li>'
echo '<li class="menu-item-has-children">'
echo '<a href="#">Single Product Layout</a>'
echo '<ul class="dropdown">'
echo '<li><a href="blog-post-left.html">Left Sidebar</a></li>'
echo '<li><a href="blog-post-right.html">Right Sidebar</a></li>'
echo '<li><a href="blog-post-fullwidth.html">No Sidebar</a></li>'
echo '</ul>'
echo '</li>'
echo '</ul>'
echo '</li>'
echo '<li class="menu-item-has-children">'
echo '<a href="#">Страницы</a>'
echo '<ul class="dropdown">'
echo '<li><a href="page-about.html">О нас</a></li>'
echo '<li><a href="page-contact.html">Контакты</a></li>'
echo '<li><a href="page-account.html">Мой аккаунт</a></li>'
echo '<li><a href="page-login.html">Вход</a></li>'
echo '<li><a href="page-register.html">Регистрация</a></li>'
echo '<li><a href="page-forgot-password.html">Забыли пароль</a></li>'
echo '<li><a href="page-reset-password.html">Сбросить пароль</a></li>'
echo '<li><a href="page-purchase-guide.html">Руководство по покупке</a></li>'
echo '<li><a href="page-privacy-policy.html">Политика конфиденциальности</a></li>'
echo '<li><a href="page-terms.html">Условия обслуживания</a></li>'
echo '<li><a href="page-404.html">404 страница</a></li>'
echo '</ul>'
echo '</li>'
echo ''
echo '</ul>'
echo '</nav>'
echo '<!-------------------------------------Низ меню mobile menu end ------------------------------------------------------------->'
echo '</div>'
echo '<div class="mobile-header-info-wrap">'
echo '<div class="single-mobile-header-info">'
echo '<a href="page-contact.html"><i class="fi-rs-marker"></i> Our location </a>'
echo '</div>'
echo '<div class="single-mobile-header-info">'
echo '<a href="page-login.html"><i class="fi-rs-user"></i>Log In / Sign Up </a>'
echo '</div>'
echo '<div class="single-mobile-header-info">'
echo '<a href="tel:+79162858833"><i class="fi-rs-headphones"></i>+7 916 285 88 33</a>'
echo '</div>'
echo '</div>'
echo '<div class="mobile-social-icon mb-50">'
echo '<h6 class="mb-15">Follow Us</h6>'
echo '<a href="#"><img src="assets/imgs/theme/icons/icon-facebook-white.svg" alt="" /></a>'
echo '<a href="#"><img src="assets/imgs/theme/icons/icon-twitter-white.svg" alt="" /></a>'
echo '<a href="#"><img src="assets/imgs/theme/icons/icon-instagram-white.svg" alt="" /></a>'
echo '<a href="#"><img src="assets/imgs/theme/icons/icon-pinterest-white.svg" alt="" /></a>'
echo '<a href="#"><img src="assets/imgs/theme/icons/icon-youtube-white.svg" alt="" /></a>'
echo '</div>'
echo '<div class="site-copyright">Copyright 2022 © Nest. All rights reserved. Powered by AliThemes.</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<!--End header-->'
echo '<main class="main pages">'
echo '<div class="page-header breadcrumb-wrap">'
echo '<div class="container">'
echo '<div class="breadcrumb">'
echo '<a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Главная</a>'
echo '<span></span> Магазин <span></span> Мой аккаунт'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="page-content pt-150 pb-150">'
echo '<div class="container">'
echo '<div class="row">'
echo '<div class="col-lg-10 m-auto">'
echo '<div class="row">'
echo '<div class="col-md-3">'
echo '<div class="dashboard-menu">'
echo '<ul class="nav flex-column" role="tablist">'
echo '<li class="nav-item">'
echo '<a class="nav-link active" id="dashboard-tab" data-bs-toggle="tab" href="#dashboard" role="tab" aria-controls="dashboard" aria-selected="false"><i class="fi-rs-settings-sliders mr-10"></i>Информационная панель</a>'
echo '</li>'
echo '<li class="nav-item">'
echo '<a class="nav-link" id="orders-tab" data-bs-toggle="tab" href="#orders" role="tab" aria-controls="orders" aria-selected="false"><i class="fi-rs-shopping-bag mr-10"></i>Заказы</a>'
echo '</li>'
echo '<li class="nav-item">'
echo '<a class="nav-link" id="track-orders-tab" data-bs-toggle="tab" href="#track-orders" role="tab" aria-controls="track-orders" aria-selected="false"><i class="fi-rs-shopping-cart-check mr-10"></i>Отследить заказ</a>'
echo '</li>'
echo '<li class="nav-item">'
echo '<a class="nav-link" id="address-tab" data-bs-toggle="tab" href="#address" role="tab" aria-controls="address" aria-selected="true"><i class="fi-rs-marker mr-10"></i>Мой адрес</a>'
echo '</li>'
echo '<li class="nav-item">'
echo '<a class="nav-link" id="account-detail-tab" data-bs-toggle="tab" href="#account-detail" role="tab" aria-controls="account-detail" aria-selected="true"><i class="fi-rs-user mr-10"></i>Данные учетной записи</a>'
echo '</li>'
echo '<li class="nav-item">'
echo '<a class="nav-link" href="page-login.html"><i class="fi-rs-sign-out mr-10"></i>Выход</a>'
echo '</li>'
echo '</ul>'
echo '</div>'
echo '</div>'
echo '<div class="col-md-9">'
echo '<div class="tab-content account dashboard-content pl-50">'
echo '<div class="tab-pane fade active show" id="dashboard" role="tabpanel" aria-labelledby="dashboard-tab">'
echo '<div class="card">'
echo '<div class="card-header">'
echo '<h3 class="mb-0">Привет Александр!</h3>'
echo '</div>'
echo '<div class="card-body">'
echo '<p>'
echo 'С панели управления вашей учетной записи. вы можете легко проверить и просмотреть свои <a href="#">последние заказы</a>,<br />'
echo 'управляйте своим <a href="#">адресом доставки и выставления счетов</a> в <a href="#">измените свой пароль и данные учетной записи.</a>'
echo '</p>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="tab-pane fade" id="orders" role="tabpanel" aria-labelledby="orders-tab">'
echo '<div class="card">'
echo '<div class="card-header">'
echo '<h3 class="mb-0">Ваши заказы</h3>'
echo '</div>'
echo '<div class="card-body">'
echo '<div class="table-responsive">'
echo '<table class="table">'
echo '<thead>'
echo '<tr>'
echo '<th>Заказать</th>'
echo '<th>Дата</th>'
echo '<th>Статус</th>'
echo '<th>Всего</th>'
echo '<th>Действия</th>'
echo '</tr>'
echo '</thead>'
echo '<tbody>'
echo '<tr>'
echo '<td>#1357</td>'
echo '<td>March 45, 2020</td>'
echo '<td>Processing</td>'
echo '<td>$125.00 for 2 item</td>'
echo '<td><a href="#" class="btn-small d-block">Вид</a></td>'
echo '</tr>'
echo '<tr>'
echo '<td>#2468</td>'
echo '<td>June 29, 2020</td>'
echo '<td>Completed</td>'
echo '<td>$364.00 for 5 item</td>'
echo '<td><a href="#" class="btn-small d-block">Вид</a></td>'
echo '</tr>'
echo '<tr>'
echo '<td>#2366</td>'
echo '<td>August 02, 2020</td>'
echo '<td>Completed</td>'
echo '<td>$280.00 for 3 item</td>'
echo '<td><a href="#" class="btn-small d-block">Вид</a></td>'
echo '</tr>'
echo '</tbody>'
echo '</table>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="tab-pane fade" id="track-orders" role="tabpanel" aria-labelledby="track-orders-tab">'
echo '<div class="card">'
echo '<div class="card-header">'
echo '<h3 class="mb-0">Отслеживание заказов</h3>'
echo '</div>'
echo '<div class="card-body contact-from-area">'
echo '<p>Чтобы отследить свой заказ, пожалуйста, введите свой идентификатор заказа в поле ниже и нажмите кнопку "Отследить". Он был указан в вашем чеке и в электронном подтверждении, которое вы должны были получить.</p>'
echo '<div class="row">'
echo '<div class="col-lg-8">'
echo '<form class="contact-form-style mt-30 mb-50" action="#" method="post">'
echo '<div class="input-style mb-20">'
echo '<label>Идентификатор заказа "Order ID"</label>'
echo '<input name="order-id" placeholder="Найдено в вашем электронном письме с подтверждением заказа" type="text" />'
echo '</div>'
echo '<div class="input-style mb-20">'
echo '<label>Электронная почта для выставления счетов</label>'
echo '<input name="billing-email" placeholder="Адрес электронной почты, который вы использовали при оформлении заказа" type="email" />'
echo '</div>'
echo '<button class="submit submit-auto-width" type="submit">Трек</button>'
echo '</form>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="tab-pane fade" id="address" role="tabpanel" aria-labelledby="address-tab">'
echo '<div class="row">'
echo '<div class="col-lg-6">'
echo '<div class="card mb-3 mb-lg-0">'
echo '<div class="card-header">'
echo '<h3 class="mb-0">Адрес для выставления счета</h3>'
echo '</div>'
echo '<div class="card-body">'
echo '<address>'
echo '3522 Interstate<br />'
echo '75 Business Spur,<br />'
echo 'Sault Ste. <br />Marie, MI 49783'
echo '</address>'
echo '<p>New York</p>'
echo '<a href="#" class="btn-small">Редактировать</a>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="col-lg-6">'
echo '<div class="card">'
echo '<div class="card-header">'
echo '<h5 class="mb-0">Адрес доставки</h5>'
echo '</div>'
echo '<div class="card-body">'
echo '<address>'
echo '4299 Express Lane<br />'
echo 'Sarasota, <br />FL 34249 USA <br />Phone: 1.941.227.4444'
echo '</address>'
echo '<p>Sarasota</p>'
echo '<a href="#" class="btn-small">Редактировать</a>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="tab-pane fade" id="account-detail" role="tabpanel" aria-labelledby="account-detail-tab">'
echo '<div class="card">'
echo '<div class="card-header">'
echo '<h5>Данные учетной записи</h5>'
echo '</div>'
echo '<div class="card-body">'
echo '<p>У вас уже есть учетная запись? <a href="page-login.html">Войдите вместо этого в систему!</a></p>'
echo '<form method="post" name="enq">'
echo '<div class="row">'
echo '<div class="form-group col-md-6">'
echo '<label>Имя <span class="required">*</span></label>'
echo '<input required="" class="form-control" name="name" type="text" />'
echo '</div>'
echo '<div class="form-group col-md-6">'
echo '<label>Фамилия <span class="required">*</span></label>'
echo '<input required="" class="form-control" name="phone" />'
echo '</div>'
echo '<div class="form-group col-md-12">'
echo '<label>Отображаемое имя <span class="required">*</span></label>'
echo '<input required="" class="form-control" name="dname" type="text" />'
echo '</div>'
echo '<div class="form-group col-md-12">'
echo '<label>Адрес электронной почты  <span class="required">*</span></label>'
echo '<input required="" class="form-control" name="email" type="email" />'
echo '</div>'
echo '<div class="form-group col-md-12">'
echo '<label>Текущий пароль <span class="required">*</span></label>'
echo '<input required="" class="form-control" name="password" type="password" />'
echo '</div>'
echo '<div class="form-group col-md-12">'
echo '<label>Новый пароль <span class="required">*</span></label>'
echo '<input required="" class="form-control" name="npassword" type="password" />'
echo '</div>'
echo '<div class="form-group col-md-12">'
echo '<label>Подтвердите пароль <span class="required">*</span></label>'
echo '<input required="" class="form-control" name="cpassword" type="password" />'
echo '</div>'
echo '<div class="col-md-12">'
echo '<button type="submit" class="btn btn-fill-out submit font-weight-bold" name="submit" value="Submit">Подтвердите пароль</button>'
echo '</div>'
echo '</div>'
echo '</form>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</main>'
echo '<footer class="main">'
echo '<section class="newsletter mb-15">'
echo '<div class="container">'
echo '<div class="row">'
echo '<div class="col-lg-12">'
echo '<div class="position-relative newsletter-inner">'
echo '<div class="newsletter-content">'
echo '<h2 class="mb-20">'
echo 'Оставайтесь дома & покупайте цветы любимым! <br />'
echo 'В нашем интернет магазине'
echo '</h2>'
echo '<p class="mb-45">Подпишись! что б не пропустить <span class="text-brand">Само ВАЖНОЕ</span></p>'
echo '<form class="form-subcriber d-flex">'
echo '<input type="email" placeholder="Ваш электронный адрес..." />'
echo '<button class="btn" type="submit">Подписаться</button>'
echo '</form>'
echo '</div>'
echo ''
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</section>'
echo '<section class="featured section-padding">'
echo '<div class="container">'
echo '<div class="row">'
echo '<div class="col-lg-1-5 col-md-4 col-12 col-sm-6 mb-md-4 mb-xl-0">'
echo '<div class="banner-left-icon d-flex align-items-center wow fadeIn animated">'
echo '<div class="banner-icon">'
echo '<img src="assets/imgs/theme/icons/icon-1.svg" alt="" />'
echo '</div>'
echo '<div class="banner-text">'
echo '<h3 class="icon-box-title">Лучшие цены и предложения!</h3>'
echo '<p>Всегда свежие цветы.</p>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="col-lg-1-5 col-md-4 col-12 col-sm-6">'
echo '<div class="banner-left-icon d-flex align-items-center wow fadeIn animated">'
echo '<div class="banner-icon">'
echo '<img src="assets/imgs/theme/icons/icon-2.svg" alt="" />'
echo '</div>'
echo '<div class="banner-text">'
echo '<h3 class="icon-box-title">Бесплатная доставка!</h3>'
echo '<p>Работаем 24/7</p>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="col-lg-1-5 col-md-4 col-12 col-sm-6">'
echo '<div class="banner-left-icon d-flex align-items-center wow fadeIn animated">'
echo '<div class="banner-icon">'
echo '<img src="assets/imgs/theme/icons/icon-3.svg" alt="" />'
echo '</div>'
echo '<div class="banner-text">'
echo '<h3 class="icon-box-title">Отличное ежедневное предложение</h3>'
echo '<p>Когда вы зарегистрируетесь</p>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="col-lg-1-5 col-md-4 col-12 col-sm-6">'
echo '<div class="banner-left-icon d-flex align-items-center wow fadeIn animated">'
echo '<div class="banner-icon">'
echo '<img src="assets/imgs/theme/icons/icon-4.svg" alt="" />'
echo '</div>'
echo '<div class="banner-text">'
echo '<h3 class="icon-box-title">Широкий ассортимент</h3>'
echo '<p>Мега Скидки</p>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="col-lg-1-5 col-md-4 col-12 col-sm-6">'
echo '<div class="banner-left-icon d-flex align-items-center wow fadeIn animated">'
echo '<div class="banner-icon">'
echo '<img src="assets/imgs/theme/icons/icon-5.svg" alt="" />'
echo '</div>'
echo '<div class="banner-text">'
echo '<h3 class="icon-box-title">Открытка бесплатно</h3>'
echo '<p>Если нужно Анонимность подарка гарантируем!</p>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<div class="col-lg-1-5 col-md-4 col-12 col-sm-6 d-xl-none">'
echo '<div class="banner-left-icon d-flex align-items-center wow fadeIn animated">'
echo '<div class="banner-icon">'
echo '<img src="assets/imgs/theme/icons/icon-6.svg" alt="" />'
echo '</div>'
echo '<div class="banner-text">'
echo '<h3 class="icon-box-title">Safe delivery</h3>'
echo '<p>Within 30 days</p>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</section>'
echo '<section class="section-padding footer-mid">'
echo '<div class="container pt-15 pb-20">'
echo '<div class="row">'
echo '<div class="col">'
echo '<div class="widget-about font-md mb-md-3 mb-lg-3 mb-xl-0">'
echo '<div class="logo mb-30">'
echo '<a href="index.html"><img src="assets/imgs/theme/логом.png" width="100" height="90" alt="logo" /></a>'
echo '<p class="font-lg text-heading">PRINCE FLOWERS USHAKOV</p>'
echo '</div>'
echo '<ul class="contact-infor">'
echo '<li><img src="assets/imgs/theme/icons/icon-location.svg" alt="" /><strong>Address: </strong> <span>5171 W Campbell Ave undefined Kent, Utah 53127 United States</span></li>'
echo '<li><img src="assets/imgs/theme/icons/icon-contact.svg" alt="" /><strong>Call Us:</strong><span>(+91) - 540-025-124553</span></li>'
echo '<li><img src="assets/imgs/theme/icons/icon-email-2.svg" alt="" /><strong>Email:</strong><span>sale@Nest.com</span></li>'
echo '<li><img src="assets/imgs/theme/icons/icon-clock.svg" alt="" /><strong>Hours:</strong><span>10:00 - 18:00, Mon - Sat</span></li>'
echo '</ul>'
echo '</div>'
echo '</div>'
echo '<div class="footer-link-widget col">'
echo '<h4 class="widget-title">Company</h4>'
echo '<ul class="footer-list mb-sm-5 mb-md-0">'
echo '<li><a href="#">About Us</a></li>'
echo '<li><a href="#">Delivery Information</a></li>'
echo '<li><a href="#">Privacy Policy</a></li>'
echo '<li><a href="#">Terms &amp; Conditions</a></li>'
echo '<li><a href="#">Contact Us</a></li>'
echo '<li><a href="#">Support Center</a></li>'
echo '<li><a href="#">Careers</a></li>'
echo '</ul>'
echo '</div>'
echo '<div class="footer-link-widget col">'
echo '<h4 class="widget-title">Account</h4>'
echo '<ul class="footer-list mb-sm-5 mb-md-0">'
echo '<li><a href="#">Sign In</a></li>'
echo '<li><a href="#">View Cart</a></li>'
echo '<li><a href="#">My Wishlist</a></li>'
echo '<li><a href="#">Track My Order</a></li>'
echo '<li><a href="#">Help Ticket</a></li>'
echo '<li><a href="#">Shipping Details</a></li>'
echo '<li><a href="#">Compare products</a></li>'
echo '</ul>'
echo '</div>'
echo '<div class="footer-link-widget col">'
echo '<h4 class="widget-title">Corporate</h4>'
echo '<ul class="footer-list mb-sm-5 mb-md-0">'
echo '<li><a href="#">Become a Vendor</a></li>'
echo '<li><a href="#">Affiliate Program</a></li>'
echo '<li><a href="#">Farm Business</a></li>'
echo '<li><a href="#">Farm Careers</a></li>'
echo '<li><a href="#">Our Suppliers</a></li>'
echo '<li><a href="#">Accessibility</a></li>'
echo '<li><a href="#">Promotions</a></li>'
echo '</ul>'
echo '</div>'
echo '<div class="footer-link-widget col">'
echo '<h4 class="widget-title">Popular</h4>'
echo '<ul class="footer-list mb-sm-5 mb-md-0">'
echo '<li><a href="#">Milk & Flavoured Milk</a></li>'
echo '<li><a href="#">Butter and Margarine</a></li>'
echo '<li><a href="#">Eggs Substitutes</a></li>'
echo '<li><a href="#">Marmalades</a></li>'
echo '<li><a href="#">Sour Cream and Dips</a></li>'
echo '<li><a href="#">Tea & Kombucha</a></li>'
echo '<li><a href="#">Cheese</a></li>'
echo '</ul>'
echo '</div>'
echo '<div class="footer-link-widget widget-install-app col">'
echo '<h4 class="widget-title">Install App</h4>'
echo '<p class="wow fadeIn animated">From App Store or Google Play</p>'
echo '<div class="download-app">'
echo '<a href="#" class="hover-up mb-sm-2 mb-lg-0"><img class="active" src="assets/imgs/theme/app-store.jpg" alt="" /></a>'
echo '<a href="#" class="hover-up mb-sm-2"><img src="assets/imgs/theme/google-play.jpg" alt="" /></a>'
echo '</div>'
echo '<p class="mb-20">Secured Payment Gateways</p>'
echo '<img class="wow fadeIn animated" src="assets/imgs/theme/payment-method.png" alt="" />'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</section>'
echo '<div class="container pb-30">'
echo '<div class="row align-items-center">'
echo '<div class="col-12 mb-30">'
echo '<div class="footer-bottom"></div>'
echo '</div>'
echo '<div class="col-xl-4 col-lg-6 col-md-6">'
echo '<p class="font-sm mb-0">&copy; 2022, <strong class="text-brand">Nest</strong> - HTML Ecommerce Template <br />All rights reserved</p>'
echo '</div>'
echo '<div class="col-xl-4 col-lg-6 text-center d-none d-xl-block">'
echo '<div class="hotline d-lg-inline-flex mr-30">'
echo '<img src="assets/imgs/theme/icons/phone-call.svg" alt="hotline" />'
echo '<p>1900 - 6666<span>Working 8:00 - 22:00</span></p>'
echo '</div>'
echo '<div class="hotline d-lg-inline-flex">'
echo '<img src="assets/imgs/theme/icons/phone-call.svg" alt="hotline" />'
echo '<p>1900 - 8888<span>24/7 Support Center</span></p>'
echo '</div>'
echo '</div>'
echo '<div class="col-xl-4 col-lg-6 col-md-6 text-end d-none d-md-block">'
echo '<div class="mobile-social-icon">'
echo '<h6>Follow Us</h6>'
echo '<a href="#"><img src="assets/imgs/theme/icons/icon-facebook-white.svg" alt="" /></a>'
echo '<a href="#"><img src="assets/imgs/theme/icons/icon-twitter-white.svg" alt="" /></a>'
echo '<a href="#"><img src="assets/imgs/theme/icons/icon-instagram-white.svg" alt="" /></a>'
echo '<a href="#"><img src="assets/imgs/theme/icons/icon-pinterest-white.svg" alt="" /></a>'
echo '<a href="#"><img src="assets/imgs/theme/icons/icon-youtube-white.svg" alt="" /></a>'
echo '</div>'
echo '<p class="font-sm">Up to 15% discount on your first subscribe</p>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</footer>'
echo '<!-- Preloader Start -->'
echo '<div id="preloader-active">'
echo '<div class="preloader d-flex align-items-center justify-content-center">'
echo '<div class="preloader-inner position-relative">'
echo '<div class="text-center">'
echo '<img src="assets/imgs/theme/loading.gif" alt="" />'
echo '</div>'
echo '</div>'
echo '</div>'
echo '</div>'
echo '<!-- Vendor JS-->'
echo '<script src="assets/js/vendor/modernizr-3.6.0.min.js"></script>'
echo '<script src="assets/js/vendor/jquery-3.6.0.min.js"></script>'
echo '<script src="assets/js/vendor/jquery-migrate-3.3.0.min.js"></script>'
echo '<script src="assets/js/vendor/bootstrap.bundle.min.js"></script>'
echo '<script src="assets/js/plugins/slick.js"></script>'
echo '<script src="assets/js/plugins/jquery.syotimer.min.js"></script>'
echo '<script src="assets/js/plugins/wow.js"></script>'
echo '<script src="assets/js/plugins/slider-range.js"></script>'
echo '<script src="assets/js/plugins/perfect-scrollbar.js"></script>'
echo '<script src="assets/js/plugins/magnific-popup.js"></script>'
echo '<script src="assets/js/plugins/select2.min.js"></script>'
echo '<script src="assets/js/plugins/waypoints.js"></script>'
echo '<script src="assets/js/plugins/counterup.js"></script>'
echo '<script src="assets/js/plugins/jquery.countdown.min.js"></script>'
echo '<script src="assets/js/plugins/images-loaded.js"></script>'
echo '<script src="assets/js/plugins/isotope.js"></script>'
echo '<script src="assets/js/plugins/scrollup.js"></script>'
echo '<script src="assets/js/plugins/jquery.vticker-min.js"></script>'
echo '<script src="assets/js/plugins/jquery.theia.sticky.js"></script>'
echo '<script src="assets/js/plugins/jquery.elevatezoom.js"></script>'
echo '<!-- Template  JS -->'
echo '<script src="./assets/js/main.js?v=5.6"></script>'
echo '<script src="./assets/js/shop.js?v=5.6"></script>'
echo '</body>'
echo ''
echo '</html>'
?>